version: '3'
services:
  app-server:
    build:
      context: ../
      dockerfile: docker/app-server/Dockerfile
    container_name: "api"
    ports:
      - "8080:8080"
  front-server:
    build:
      context: ../
      dockerfile: docker/front-server/Dockerfile
    container_name: "front"
    ports:
      - "3000:3000"
    command: yarn run serve
    stdin_open: true
    tty: true
